# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: t1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='t1.proto',
  package='cloudmb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08t1.proto\x12\x07\x63loudmb\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x1f\n\nStringList\x12\x11\n\tArguments\x18\x01 \x03(\t\".\n\x08\x44\x61taList\x12\"\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\"\xad\x01\n\x07MbReply\x12\x0f\n\x07Subject\x18\x01 \x01(\t\x1a\\\n\x05Value\x12\x0b\n\x03PID\x18\x01 \x01(\x05\x12\x0c\n\x04\x45xit\x18\x02 \x01(\x05\x12\x0f\n\x07Message\x18\x03 \x01(\t\x12\'\n\x06Result\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\"3\n\x04Type\x12\n\n\x06STATUS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\n\n\x06RESULT\x10\x02\x12\x08\n\x04INFO\x10\x03\"Q\n\tMbCommand\x12\x0b\n\x03\x43md\x18\x01 \x01(\t\x12&\n\tArguments\x18\x02 \x01(\x0b\x32\x13.cloudmb.StringList\x12\x0f\n\x07Subject\x18\x03 \x01(\t\"\xf4\x01\n\x07\x43\x66\x64Info\x12\x10\n\x08Progress\x18\x01 \x01(\x05\x12\x0c\n\x04\x45xit\x18\x02 \x01(\x05\x12\x0c\n\x04\x44one\x18\x03 \x01(\x05\x1a\xba\x01\n\x06Result\x12$\n\x04Mesh\x18\x01 \x01(\x0b\x32\x14.cloudmb.CfdMeshInfoH\x00\x12+\n\tResiduals\x18\x02 \x01(\x0b\x32\x16.cloudmb.CfdSolverInfoH\x00\x12)\n\x06Result\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x12*\n\x04\x44\x61ta\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.ListValueH\x00\x42\x06\n\x04kind\"A\n\x0b\x43\x66\x64MeshInfo\x12\x0e\n\x06ncells\x18\x01 \x01(\x05\x12\x0e\n\x06\x66\x61iled\x18\x02 \x01(\x05\x12\x12\n\nemptypatch\x18\x03 \x01(\t\"2\n\rCfdSolverInfo\x12\x11\n\tresiduals\x18\x01 \x03(\x01\x12\x0e\n\x06\x66ields\x18\x02 \x03(\tb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])



_MBREPLY_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='cloudmb.MbReply.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=282,
  serialized_end=333,
)
_sym_db.RegisterEnumDescriptor(_MBREPLY_TYPE)


_STRINGLIST = _descriptor.Descriptor(
  name='StringList',
  full_name='cloudmb.StringList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Arguments', full_name='cloudmb.StringList.Arguments', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=109,
)


_DATALIST = _descriptor.Descriptor(
  name='DataList',
  full_name='cloudmb.DataList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Data', full_name='cloudmb.DataList.Data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=157,
)


_MBREPLY_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='cloudmb.MbReply.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='PID', full_name='cloudmb.MbReply.Value.PID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Exit', full_name='cloudmb.MbReply.Value.Exit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Message', full_name='cloudmb.MbReply.Value.Message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Result', full_name='cloudmb.MbReply.Value.Result', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=280,
)

_MBREPLY = _descriptor.Descriptor(
  name='MbReply',
  full_name='cloudmb.MbReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Subject', full_name='cloudmb.MbReply.Subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MBREPLY_VALUE, ],
  enum_types=[
    _MBREPLY_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=333,
)


_MBCOMMAND = _descriptor.Descriptor(
  name='MbCommand',
  full_name='cloudmb.MbCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cmd', full_name='cloudmb.MbCommand.Cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Arguments', full_name='cloudmb.MbCommand.Arguments', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Subject', full_name='cloudmb.MbCommand.Subject', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=416,
)


_CFDINFO_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='cloudmb.CfdInfo.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Mesh', full_name='cloudmb.CfdInfo.Result.Mesh', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Residuals', full_name='cloudmb.CfdInfo.Result.Residuals', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Result', full_name='cloudmb.CfdInfo.Result.Result', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Data', full_name='cloudmb.CfdInfo.Result.Data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='cloudmb.CfdInfo.Result.kind',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=477,
  serialized_end=663,
)

_CFDINFO = _descriptor.Descriptor(
  name='CfdInfo',
  full_name='cloudmb.CfdInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Progress', full_name='cloudmb.CfdInfo.Progress', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Exit', full_name='cloudmb.CfdInfo.Exit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Done', full_name='cloudmb.CfdInfo.Done', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CFDINFO_RESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=663,
)


_CFDMESHINFO = _descriptor.Descriptor(
  name='CfdMeshInfo',
  full_name='cloudmb.CfdMeshInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ncells', full_name='cloudmb.CfdMeshInfo.ncells', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='failed', full_name='cloudmb.CfdMeshInfo.failed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='emptypatch', full_name='cloudmb.CfdMeshInfo.emptypatch', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=665,
  serialized_end=730,
)


_CFDSOLVERINFO = _descriptor.Descriptor(
  name='CfdSolverInfo',
  full_name='cloudmb.CfdSolverInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='residuals', full_name='cloudmb.CfdSolverInfo.residuals', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fields', full_name='cloudmb.CfdSolverInfo.fields', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=732,
  serialized_end=782,
)

_DATALIST.fields_by_name['Data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_MBREPLY_VALUE.fields_by_name['Result'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_MBREPLY_VALUE.containing_type = _MBREPLY
_MBREPLY_TYPE.containing_type = _MBREPLY
_MBCOMMAND.fields_by_name['Arguments'].message_type = _STRINGLIST
_CFDINFO_RESULT.fields_by_name['Mesh'].message_type = _CFDMESHINFO
_CFDINFO_RESULT.fields_by_name['Residuals'].message_type = _CFDSOLVERINFO
_CFDINFO_RESULT.fields_by_name['Result'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_CFDINFO_RESULT.fields_by_name['Data'].message_type = google_dot_protobuf_dot_struct__pb2._LISTVALUE
_CFDINFO_RESULT.containing_type = _CFDINFO
_CFDINFO_RESULT.oneofs_by_name['kind'].fields.append(
  _CFDINFO_RESULT.fields_by_name['Mesh'])
_CFDINFO_RESULT.fields_by_name['Mesh'].containing_oneof = _CFDINFO_RESULT.oneofs_by_name['kind']
_CFDINFO_RESULT.oneofs_by_name['kind'].fields.append(
  _CFDINFO_RESULT.fields_by_name['Residuals'])
_CFDINFO_RESULT.fields_by_name['Residuals'].containing_oneof = _CFDINFO_RESULT.oneofs_by_name['kind']
_CFDINFO_RESULT.oneofs_by_name['kind'].fields.append(
  _CFDINFO_RESULT.fields_by_name['Result'])
_CFDINFO_RESULT.fields_by_name['Result'].containing_oneof = _CFDINFO_RESULT.oneofs_by_name['kind']
_CFDINFO_RESULT.oneofs_by_name['kind'].fields.append(
  _CFDINFO_RESULT.fields_by_name['Data'])
_CFDINFO_RESULT.fields_by_name['Data'].containing_oneof = _CFDINFO_RESULT.oneofs_by_name['kind']
DESCRIPTOR.message_types_by_name['StringList'] = _STRINGLIST
DESCRIPTOR.message_types_by_name['DataList'] = _DATALIST
DESCRIPTOR.message_types_by_name['MbReply'] = _MBREPLY
DESCRIPTOR.message_types_by_name['MbCommand'] = _MBCOMMAND
DESCRIPTOR.message_types_by_name['CfdInfo'] = _CFDINFO
DESCRIPTOR.message_types_by_name['CfdMeshInfo'] = _CFDMESHINFO
DESCRIPTOR.message_types_by_name['CfdSolverInfo'] = _CFDSOLVERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StringList = _reflection.GeneratedProtocolMessageType('StringList', (_message.Message,), {
  'DESCRIPTOR' : _STRINGLIST,
  '__module__' : 't1_pb2'
  # @@protoc_insertion_point(class_scope:cloudmb.StringList)
  })
_sym_db.RegisterMessage(StringList)

DataList = _reflection.GeneratedProtocolMessageType('DataList', (_message.Message,), {
  'DESCRIPTOR' : _DATALIST,
  '__module__' : 't1_pb2'
  # @@protoc_insertion_point(class_scope:cloudmb.DataList)
  })
_sym_db.RegisterMessage(DataList)

MbReply = _reflection.GeneratedProtocolMessageType('MbReply', (_message.Message,), {

  'Value' : _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
    'DESCRIPTOR' : _MBREPLY_VALUE,
    '__module__' : 't1_pb2'
    # @@protoc_insertion_point(class_scope:cloudmb.MbReply.Value)
    })
  ,
  'DESCRIPTOR' : _MBREPLY,
  '__module__' : 't1_pb2'
  # @@protoc_insertion_point(class_scope:cloudmb.MbReply)
  })
_sym_db.RegisterMessage(MbReply)
_sym_db.RegisterMessage(MbReply.Value)

MbCommand = _reflection.GeneratedProtocolMessageType('MbCommand', (_message.Message,), {
  'DESCRIPTOR' : _MBCOMMAND,
  '__module__' : 't1_pb2'
  # @@protoc_insertion_point(class_scope:cloudmb.MbCommand)
  })
_sym_db.RegisterMessage(MbCommand)

CfdInfo = _reflection.GeneratedProtocolMessageType('CfdInfo', (_message.Message,), {

  'Result' : _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
    'DESCRIPTOR' : _CFDINFO_RESULT,
    '__module__' : 't1_pb2'
    # @@protoc_insertion_point(class_scope:cloudmb.CfdInfo.Result)
    })
  ,
  'DESCRIPTOR' : _CFDINFO,
  '__module__' : 't1_pb2'
  # @@protoc_insertion_point(class_scope:cloudmb.CfdInfo)
  })
_sym_db.RegisterMessage(CfdInfo)
_sym_db.RegisterMessage(CfdInfo.Result)

CfdMeshInfo = _reflection.GeneratedProtocolMessageType('CfdMeshInfo', (_message.Message,), {
  'DESCRIPTOR' : _CFDMESHINFO,
  '__module__' : 't1_pb2'
  # @@protoc_insertion_point(class_scope:cloudmb.CfdMeshInfo)
  })
_sym_db.RegisterMessage(CfdMeshInfo)

CfdSolverInfo = _reflection.GeneratedProtocolMessageType('CfdSolverInfo', (_message.Message,), {
  'DESCRIPTOR' : _CFDSOLVERINFO,
  '__module__' : 't1_pb2'
  # @@protoc_insertion_point(class_scope:cloudmb.CfdSolverInfo)
  })
_sym_db.RegisterMessage(CfdSolverInfo)


# @@protoc_insertion_point(module_scope)
