(defun find-max-min-array (my-array)
  (if (array-rank my-array)
      (let* ((dimensions (array-dimensions my-array))
             (n-dimensions (length dimensions))
             (a-indices (make-list n-dimensions :initial-element 0))
             (max-value (aref my-array a-indices))
             (min-value (aref my-array a-indices)))
        (dotimes (i n-dimensions)
          (dotimes (j (expt 2 i))
            (setf (nth i a-indices) j)
            (let ((current-value (aref my-array a-indices)))
              (setf max-value (max max-value current-value))
              (setf min-value (min min-value current-value)))))
        (list max-value min-value))
      (error "Array must have at least one dimension.")))

(defun list-to-2d-array (list)
  (make-array (list (length list)
                    (length (first list)))
              :initial-contents list))

(let*((l (list 1 2 3 4))
      (l2 (list l (list 5 6 7 8)))
      (a2 (list-to-2d-array l2)))
    (find-max-min-array a2))

