.PHONY: clean All

All:
	@echo "----------Building project:[ wxStartup - Debug ]----------"
	@$(MAKE) -f  "wxStartup.mk"
clean:
	@echo "----------Cleaning project:[ wxStartup - Debug ]----------"
	@$(MAKE) -f  "wxStartup.mk" clean
