######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 5 15:13:47 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cfd1d.h MyWindow.h
SOURCES += cfd1d.cpp main.cpp MyWindow.cpp
